[package]
name = "tab-organizer"
version = "5.0.0"
authors = ["Pauan"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug-assertions = true
lto = true

[dependencies]
discard = "1.0.3"
serde = "1.0.36"
serde_derive = "1.0.36"
serde_json = "1.0.13"
futures-preview = "0.3.0-alpha.7"
lazy_static = "1.0.0"
web-extensions = { path = "./web-extensions" }
uuid = { version = "0.7.1", features = ["serde"] }
stdweb = { version = "0.4.8", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }
# TODO remove this
stdweb-derive = "0.5.0"
dominator = { git = "https://github.com/Pauan/rust-dominator" }
futures-signals = { git = "https://github.com/Pauan/rust-signals" }

[patch.crates-io]
stdweb = { git = "https://github.com/koute/stdweb" }
