[package]
name = "tab-organizer"
version = "5.0.0"
authors = ["Pauan"]

[dependencies]
discard = "1.0.3"
serde = "1.0.36"
serde_derive = "1.0.36"
serde_json = "1.0.13"
futures = { version = "0.2.1", features = ["std", "nightly"] }
lazy_static = "1.0.0"
web-extensions = { path = "./web-extensions" }
uuid = { version = "0.6.2", features = ["serde"] }
stdweb = { version = "0.4.0", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }
dominator = { git = "https://github.com/Pauan/rust-dominator" }
futures-signals = { git = "https://github.com/Pauan/rust-signals" }

[profile.release]
panic = "abort"

[patch.crates-io]
futures = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-core = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-util = { git = "https://github.com/rust-lang-nursery/futures-rs" }
futures-channel = { git = "https://github.com/rust-lang-nursery/futures-rs" }
