[package]
name = "tab-organizer"
version = "5.0.0"
authors = ["Pauan"]

[dependencies]
futures = "0.1.18"
discard = "1.0.3"
web-extensions = { path = "./web-extensions" }

[profile.release]
panic = "abort"

[dependencies.stdweb]
version = "0.4.0"
features = ["experimental_features_which_may_break_on_minor_version_bumps"]
