[package]
name = "tab-organizer-background"
version = "0.1.0"
authors = ["Pauan <pauanyu+github@pm.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug-assertions = true
lto = true

[dependencies]
web-extension = { path = "../../web-extension" }
wasm-bindgen = "0.2.45"
js-sys = "0.3.27"
futures-preview = "0.3.0-alpha.16"
futures-signals = "0.3.0"
tab-organizer = { path = "../.." }
serde_json = "1.0.40"

[dependencies.wasm-bindgen-futures]
version = "0.3.22"
features = ["futures_0_3"]

[dependencies.web-sys]
version = "0.3.27"
features = [
    "console",
]

[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"
